name: Build Plugin
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install Dependencies
        run: npm install
      - name: Build Plugin
        run: npx rollup -c # This is the standard Vendetta build command
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: gofile-plugin
          path: dist/
